add NanoPhase --check

diff --git a/bin/NanoPhase b/bin/NanoPhase
--- a/bin/NanoPhase
+++ b/bin/NanoPhase
@@ -10,6 +10,7 @@ cat << EOF
 `echo "NanoPhase v=$VERSION"`
 
 arguments:
+	--check			check the package availability
 	--long_read_only	only Nanopore long reads were involved [default: on]
 	--hybrid		both short and long reads were required [Optional]
 	-l, --long		Nanopore reads: fasta/q file that basecalled by Guppy 5+ or using 20+ chemistry was recommended if only Nanopore reads were included [Mandatory]
@@ -27,6 +28,7 @@ output sub-folders:
         03-Polishing            Sub-folder containing polished bins
 
 example usage:
+	NanoPhase --check ## package availability checking
         Nanophase -l ont.fastq -t 16 -o NanoPhase-out ## long reads only
         Nanophase -l ont.fastq --hybrid -1 sr_1.fastq -2 sr_2.fastq -t 16 -o NanoPhase-out ## hybrid strategy
 
@@ -42,13 +44,14 @@ ONT_seqs=""
 #SR2_seqs=""
 CRTDIR=$(cd `dirname $0`; pwd)
 OutDIR="NanoPhase-out"
+check_pkg="false"
 medaka_model="r941_min_hac_g507"
 VERSION="0.1.0"
 
 ## call command line 
 echo -e "\nCommand line: $CRTDIR/NanoPhase $*\n" >&2
 ##
-params="$(getopt -o hl:1:2:t:o:m:v --long help,hybrid,long:,long-read-only,threads:,medaka_model:,out:,version -- "$@")"
+params="$(getopt -o hl:1:2:t:o:m:v --long help,hybrid,long:,long-read-only,threads:,medaka_model:,out:,check,version -- "$@")"
 if [[ $? -gt 0 ]]; then show_help; exit 1; fi
 if [[ $# == 0 ]]; then show_help; exit 1; fi
 
@@ -72,6 +75,7 @@ while true; do
 	esac
 done
 
+if [[ $check_pkg == false ]]; then
 # Make sure the necessary files exist, if required variables are not setup, show help information and exit
 long_read_check(){
 if [[ ! -f "$ONT_seqs" ]]; then 
@@ -928,4 +932,40 @@ echo "==========================================================================
 NanoPhase finished @`date "+%Y/%m/%d -- %H:%M:%S"`
 Have a nice day!"
 printf "\n"
+
+elif [[ $check_pkg == true ]]; then
+        echo "===========================================================================================================
+        Check software availability and locations" ## should check unavailable: if xxx then echo ""; exit 1
+        rm -rf .package.installed 2>/dev/null && rm -rf .package.not.installed 2>/dev/null
+
+        echo -e "flye\nmetabat2\nrun_MaxBin.pl\nmetawrap\ncheckm\nracon\nmedaka\npolypolish\npolca.sh\nbwa\nseqtk\nminimap2\nstats.sh\nparallel\nperl\nsamtools" | while read package; do
+        if [[ "$(command -v $package)" ]]; then
+                echo -e "$package\t`which $package`" | sed -e 's/polca.sh/POLCA/1' -e 's/run_MaxBin.pl/maxbin2/1' -e 's/stats.sh/BBMap/g' | awk '{printf "%-20s %s\n", $1,$2}' >> .package.installed
+        else
+                echo "$package" | sed -e 's/polca.sh/POLCA/1' -e 's/run_MaxBin.pl/maxbin2/1' -e 's/stats.sh/BBMap/g' | awk '{printf "%-20s %s\n", $1,$2}' >> .package.not.installed
+        fi ; done
+
+        if [[ -s .package.installed ]]; then
+                echo "===========================================================================================================
+                The following packages have been found  @`date "+%Y/%m/%d -- %H:%M:%S"`"
+                cat .package.installed | sed -e '1i#package\tlocation' | awk '{printf "%-20s %s\n", $1,$2}'
+                echo "==========================================================================================================="
+        else
+                echo "No required package has been found in the environment, please install, terminating..."
+                exit 1
+        fi
+
+        if [[ ! -s .package.not.installed ]]; then
+                echo "All required packages have been found in the environment"
+                path_check=`cat .package.installed | awk '{printf "%-20s %s\n", $1,$2}' | awk '{print $2}' | while read path; do dirname $path; done | awk '!a[$1]++' | wc -l`
+                if [[ $path_check -gt 1 ]]; then
+                        echo "Warning: [`cat .package.installed | awk '{printf "%-20s %s\n", $1,$2}' | awk '{print $2}' | while read path; do dirname $path; done | grep -v 'NanoPhase\/bin' | while read line; do grep -w $line .package.installed; done | awk '!a[$1]++ {print $1}' | tr '\n' ' ' | sed -e 's/ $//g'`] has not been installed in the [NanoPhase] env. Strongly recommend intalling all packages in the NanoPhase env, or it may result in a failure"
+                        rm -rf .package.installed
+                fi
+        else
+                echo "Error: [`cat .package.not.installed | sed -e 's/ //g' | tr '\n' ' ' | sed -e 's/ $//g'`] cannot be found in the environment, please install. Now terminating..."
+                rm -rf .package.not.installed && rm -rf .package.installed
+        fi
+fi
+
 
